version: '3.8'

services:
  sismo-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sismo-monitor
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - MIN_MAGNITUDE=4.5
      - MONITOR_INTERVAL=1m
      - MIN_LATITUDE=-90.0
      - MAX_LATITUDE=90.0
      - MIN_LONGITUDE=-180.0
      - MAX_LONGITUDE=180.0
